### ISSUE TITLE
UI Design for the Chrome Extension

### ISSUE THREAD

**Issue by RashikaKarki** [RashikaKarki/WomenHack#1]
Here is the rough design we made while discussing but we do need to clean it up a bit. 

![image](https://user-images.githubusercontent.com/41114269/114259513-2bbced00-99ee-11eb-9ffd-ed447b07cd9b.png)

**Comment by anicoletoo** [comment]
Here is a mockup of the extension design:
![extension_design](https://user-images.githubusercontent.com/40279355/114278728-fdd3aa80-99e5-11eb-90b0-2a676ff8ec24.png)
An interactive version can be found on [Figma](https://www.figma.com/file/inUEcB154ykHkThM1uBXTF/Break-Extension?node-id=0%3A1
)
